"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import "./channels.css";

type Connection = { id: string; artistId: string; artistName: string; provider: string; displayName: string; status: string; connectedAt: string; lastCheckedAt: string | null; lastWebhookAt: string | null; lastError: string | null };
type Setup = { connections: Connection[]; artists: Array<{ id: string; name: string }>; mode: string; configured: boolean; missing: string[]; redirectUri: string; webhookUrl: string };
type Candidate = { setupId: string; artistId: string; pages: Array<{ id: string; name: string; instagram: { id: string; username?: string; name?: string } | null }> };
async function json<T>(response: Response) { const data = await response.json(); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Request failed"); return data as T; }
function when(value: string | null) { return value ? new Date(value).toLocaleString() : "Not yet"; }

const oauthErrors: Record<string, string> = {
  "meta-access-denied": "Meta access was cancelled or denied.",
  "meta-missing-callback": "Meta returned an incomplete authorization response.",
  "meta-state-expired": "The Meta connection request expired. Start again.",
  "meta-no-pages": "No eligible Facebook Pages were returned. Confirm that you manage the Page and that it is linked to the Instagram professional account.",
  "meta-oauth-failed": "Meta authorization failed. Confirm the app permissions and redirect URI, then try again.",
};

export default function ChannelsPage() {
  const [setup, setSetup] = useState<Setup>({ connections: [], artists: [], mode: "live", configured: false, missing: [], redirectUri: "", webhookUrl: "" });
  const [artistId, setArtistId] = useState("");
  const [provider, setProvider] = useState("INSTAGRAM");
  const [displayName, setDisplayName] = useState("Embellished Studios");
  const [test, setTest] = useState({ connectionId: "", senderId: "test-client-1", senderName: "Jordan Client", text: "Hi, how much would a fine-line tattoo cost?" });
  const [candidate, setCandidate] = useState<Candidate | null>(null);
  const [selectedPageId, setSelectedPageId] = useState("");
  const [connectFacebook, setConnectFacebook] = useState(true);
  const [connectInstagram, setConnectInstagram] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { const data = await json<Setup>(await fetch("/api/channels", { cache: "no-store" })); setSetup(data); setArtistId(value => value || data.artists[0]?.id || ""); setTest(value => ({ ...value, connectionId: value.connectionId || data.connections.find(item => item.status === "ACTIVE")?.id || "" })); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load channels"); } }, []);

  useEffect(() => {
    void refresh();
    const params = new URLSearchParams(window.location.search);
    const error = params.get("error");
    if (error) setMessage(oauthErrors[error] || "Meta connection could not be completed.");
    const setupId = params.get("metaSetup");
    if (setupId) void fetch(`/api/channels/meta-candidates?setupId=${encodeURIComponent(setupId)}`, { cache: "no-store" }).then(response => json<Candidate>(response)).then(data => { setCandidate(data); setSelectedPageId(data.pages[0]?.id || ""); setConnectInstagram(Boolean(data.pages[0]?.instagram)); }).catch(problem => setMessage(problem instanceof Error ? problem.message : "Unable to load Meta accounts"));
  }, [refresh]);

  async function post(body: unknown) { return json(await fetch("/api/channels", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })); }
  async function mockConnect(event: FormEvent) { event.preventDefault(); setBusy(true); try { await post({ action: "CONNECT_MOCK", artistId, provider, displayName }); setMessage(`${provider === "INSTAGRAM" ? "Instagram" : "Facebook"} test account connected.`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to connect"); } finally { setBusy(false); } }
  async function disconnect(connectionId: string) { setBusy(true); try { await post({ action: "DISCONNECT", connectionId }); setMessage("Social account disconnected."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to disconnect"); } finally { setBusy(false); } }
  async function checkHealth(connectionId: string) { setBusy(true); try { const result = await post({ action: "CHECK_HEALTH", connectionId }) as { status: string; error?: string | null }; setMessage(result.status === "ACTIVE" ? "Meta connection is healthy and subscribed." : result.error || "Meta connection needs attention."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to check connection"); } finally { setBusy(false); } }
  async function connectSelected(event: FormEvent) { event.preventDefault(); if (!candidate) return; setBusy(true); try { const result = await json<{ connected: number }>(await fetch("/api/channels/meta-candidates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ setupId: candidate.setupId, pageId: selectedPageId, connectFacebook, connectInstagram }) })); setMessage(`${result.connected} social channel${result.connected === 1 ? "" : "s"} connected.`); setCandidate(null); window.history.replaceState({}, "", "/channels"); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to connect selected account"); } finally { setBusy(false); } }
  async function simulate(event: FormEvent) { event.preventDefault(); setBusy(true); try { const result = await json<{ aiReplied?: boolean }>(await fetch("/api/channels/mock-inbound", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(test) })); setMessage(result.aiReplied ? "Test DM received and answered by the AI. Open Inbox to review it." : "Test DM received. AI did not reply because this conversation is under human control, closed, or delivery failed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to simulate message"); } finally { setBusy(false); } }
  const selectedPage = candidate?.pages.find(page => page.id === selectedPageId);

  return <main className="channels-page"><header><a href="/settings">← Owner settings</a><h1>Social messaging</h1><p>Connect each artist&apos;s Instagram professional account and Facebook Page to the unified inbox.</p></header>{message && <div className="channel-notice">{message}</div>}
    <section className="channel-card"><div><h2>Meta connection</h2><p>{setup.mode === "mock" ? "Mock mode is active. No messages leave the application." : setup.configured ? "Meta OAuth is configured. Select the artist, authorize Meta, and then choose the exact Page to connect." : `Meta configuration is incomplete${setup.missing.length ? `: ${setup.missing.join(", ")}` : "."}`}</p></div><label>Artist<select value={artistId} onChange={event => setArtistId(event.target.value)}>{setup.artists.map(artist => <option key={artist.id} value={artist.id}>{artist.name}</option>)}</select></label>{setup.mode === "mock" ? <form className="mock-connect" onSubmit={mockConnect}><label>Channel<select value={provider} onChange={event => setProvider(event.target.value)}><option value="INSTAGRAM">Instagram</option><option value="FACEBOOK">Facebook</option></select></label><label>Account name<input value={displayName} onChange={event => setDisplayName(event.target.value)} /></label><button disabled={busy || !artistId}>Connect test account</button></form> : <a className={`connect-button ${!setup.configured || !artistId ? "disabled" : ""}`} href={setup.configured && artistId ? `/api/integrations/meta/connect?artistId=${artistId}` : undefined}>Continue with Facebook</a>}</section>
    {candidate && <form className="channel-card account-picker" onSubmit={connectSelected}><h2>Choose the account to connect</h2><p>Only the selected Page and its linked Instagram professional account will be stored for this artist.</p><label>Facebook Page<select value={selectedPageId} onChange={event => { const value = event.target.value; setSelectedPageId(value); setConnectInstagram(Boolean(candidate.pages.find(page => page.id === value)?.instagram)); }}>{candidate.pages.map(page => <option key={page.id} value={page.id}>{page.name}{page.instagram?.username ? ` · @${page.instagram.username}` : ""}</option>)}</select></label><label className="channel-check"><input type="checkbox" checked={connectFacebook} onChange={event => setConnectFacebook(event.target.checked)} /> Connect Facebook Messenger</label><label className="channel-check"><input type="checkbox" checked={connectInstagram} disabled={!selectedPage?.instagram} onChange={event => setConnectInstagram(event.target.checked)} /> Connect Instagram {selectedPage?.instagram?.username ? `(@${selectedPage.instagram.username})` : "(no professional account linked)"}</label><button disabled={busy || !selectedPageId || (!connectFacebook && !connectInstagram)}>Connect selected channels</button></form>}
    <section className="channel-card"><h2>Connected accounts</h2>{setup.connections.length === 0 ? <p className="empty">No social accounts connected.</p> : setup.connections.map(connection => <div className="connection-row" key={connection.id}><div><strong>{connection.displayName} <span className={`status-pill ${connection.status.toLowerCase()}`}>{connection.status.replaceAll("_", " ")}</span></strong><span>{connection.provider} · {connection.artistName}</span><small>Health checked: {when(connection.lastCheckedAt)} · Last webhook: {when(connection.lastWebhookAt)}</small>{connection.lastError && <small className="connection-error">{connection.lastError}</small>}</div><div className="connection-actions">{setup.mode === "live" && connection.status !== "DISCONNECTED" && <button disabled={busy} onClick={() => checkHealth(connection.id)}>Check status</button>}{setup.mode === "live" && connection.status === "ACTION_REQUIRED" && <a className="secondary-link" href={`/api/integrations/meta/connect?artistId=${connection.artistId}`}>Reconnect</a>}{connection.status !== "DISCONNECTED" && <button disabled={busy} onClick={() => disconnect(connection.id)}>Disconnect</button>}</div></div>)}</section>
    {setup.mode === "mock" && <form className="channel-card" onSubmit={simulate}><h2>Simulate an inbound DM</h2><p>Use a different sender ID for each simulated client. Reusing an ID correctly continues that client&apos;s existing conversation.</p><label>Connected account<select value={test.connectionId} onChange={event => setTest({ ...test, connectionId: event.target.value })}>{setup.connections.filter(item => item.status === "ACTIVE").map(item => <option key={item.id} value={item.id}>{item.provider} · {item.displayName}</option>)}</select></label><label>Client display name<input value={test.senderName} onChange={event => setTest({ ...test, senderName: event.target.value })} /></label><label>Unique sender ID<input value={test.senderId} onChange={event => setTest({ ...test, senderId: event.target.value })} /></label><label>Message<textarea value={test.text} onChange={event => setTest({ ...test, text: event.target.value })} /></label><button disabled={busy || !test.connectionId || !test.senderId.trim() || !test.senderName.trim() || !test.text.trim()}>Send test DM into inbox</button></form>}
    {setup.mode === "live" && <section className="channel-card endpoints"><h2>Meta developer settings</h2><p>Use these exact values in the Meta developer dashboard.</p><label>OAuth redirect URI<code>{setup.redirectUri}</code></label><label>Webhook callback URL<code>{setup.webhookUrl}</code></label></section>}
    <section className="channel-card checklist"><h2>Live Meta checklist</h2><ol><li>Use an Instagram professional account linked to the Facebook Page.</li><li>Add the exact OAuth redirect and webhook callback shown above.</li><li>Subscribe the Page and Instagram webhook objects to messaging events.</li><li>Use Check status to verify the token, permissions, account, and Page subscription.</li><li>Complete Meta Business Verification and App Review before connecting customer studios.</li></ol></section>
  </main>;
}
